#!/usr/bin/env python3
"""Bundle the modular ApexFlow EA into ONE self-contained .mq5 file.

Every local `#include "..."` is inlined (depth-first, each file once, in the
same order the compiler would read it). Standard-library includes such as
`#include <Trade\\Trade.mqh>` are kept: they ship with every MetaTrader 5.

    python3 scripts/bundle.py            -> dist/ApexFlow.mq5
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENTRY = ROOT / "MQL5" / "Experts" / "ApexFlow" / "ApexFlow.mq5"
OUT = ROOT / "dist" / "ApexFlow.mq5"
LOCAL_INCLUDE = re.compile(r'^\s*#include\s+"([^"]+)"\s*$')


def inline(path: Path, seen: set[Path], out: list[str]) -> None:
    path = path.resolve()
    if path in seen:
        return
    seen.add(path)
    rel = path.relative_to(ROOT / "MQL5" / "Experts" / "ApexFlow")
    if path != ENTRY.resolve():
        out.append(f"//{'=' * 68}\n// BEGIN {rel.as_posix()}\n//{'=' * 68}\n")
    for line in path.read_text(encoding="utf-8").splitlines(keepends=True):
        m = LOCAL_INCLUDE.match(line)
        if m:
            target = (path.parent / m.group(1).replace("\\", "/")).resolve()
            if not target.exists():
                sys.exit(f"missing include {m.group(1)} in {path}")
            inline(target, seen, out)
            continue
        out.append(line)
    if not out[-1].endswith("\n"):
        out.append("\n")
    if path != ENTRY.resolve():
        out.append(f"// END {rel.as_posix()}\n\n")


def main() -> int:
    out: list[str] = [
        "//+------------------------------------------------------------------+\n",
        "//| ApexFlow.mq5 - SINGLE-FILE BUILD                                  |\n",
        "//| Generated by scripts/bundle.py from MQL5/Experts/ApexFlow/.       |\n",
        "//| Copy this one file to <DataFolder>\\MQL5\\Experts\\ and compile.      |\n",
        "//| Edit the modular sources, then regenerate; do not edit this file. |\n",
        "//+------------------------------------------------------------------+\n",
    ]
    inline(ENTRY, set(), out)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(out), encoding="utf-8")
    remaining = [l for l in "".join(out).splitlines() if LOCAL_INCLUDE.match(l)]
    if remaining:
        sys.exit(f"unresolved includes: {remaining}")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(''.join(out).splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
